os:
- linux
sudo: false
language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-27
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
env:
  global:
  - ANDROID_HOME=${TRAVIS_BUILD_DIR}/android-sdk
  - PATH=${ANDROID_HOME}/:${ANDROID_HOME}/tools/:${ANDROID_HOME}/platform-tools/:${PATH}
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - lib32stdc++6
    - fonts-droid
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- "./flutter/bin/flutter doctor"
before_install:
- openssl aes-256-cbc -K $encrypted_48c69e2e2e61_key -iv $encrypted_48c69e2e2e61_iv -in android/key.properties.enc -out android/key.properties -d
script:
- "./flutter/bin/flutter build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  name: master-current
  provider: releases
  api_key:
    secure: C9kB9Bsjnpv/QP6OHFNXBJzRgDOvaDZXCp4ycJS0cXf9HxP0WtuTKa5BZv4LehPcC17nrJE4ebUaofCb8GU1Z5CK+WJsLqoGpBJsay0Nw55RDz7vd7mU80y+jNtQbn6i8UcpkNeqCqQgYVJksU0YYPWd4/GBR/jfF35d1k+hyVD8obsPlRyP7k36RDy+pFFDrmRurjBB23BUud1cYyWLiesvULIpsFK3v3TA9spjGYxHP7LXsQC/IqCw9qXrK/FXGJXN1kpjmvGQGPDDO/1BwW1ibIU/ihqgYR7/e7wA6RLgh6Kv5FiMiM9TfFqwOcHEvrg5jb0LvmmGQyvASaapmlZQvfE4rcdOD40jmAl0oM2I3Uree6+yLNEYqg+JQh91yEaUGXWsGDxuG4nHcmgHsjIh8hN4mf8Ycspk1qBV851nkLMl+mGOEZtr6Fr2WDqXshRLF7Ffaq7BkIeyCvW8GKJm384w6Gr3TIZwRgcl1Te8jg50HVMXBL/oi1SVoNKpN6caG6tNOrBznUou3vEWYR3zKjJgFgm2KMRs76Z/cxSize0Qpv+xc5vzyQWYbLnC+Lw1z96kRMRVE/B2Vnk2AU48DQjFgsi4zKSV1d1+K09iXXjBR8LmXKVu58pI7shTCE69gTdfhz4rGJtgrO+CWCSr5OV3Ew/3yqmk1QhTvGc=
  file: build/app/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: larsjarlvik/poddy
    branch: master
