name: poddy
description: A new Flutter project.

dependencies:
  http: "^0.11.3+16"
  xml: "^3.0.0"
  flutter_html_view: "^0.5.1"
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/gradient.png
    - assets/poddy.png

  fonts:
    - family: Norwester
      fonts:
        - asset: assets/norwester.otf
